"""empty message

Revision ID: a485ac72b99a
Revises: e4065d67fdff
Create Date: 2024-07-21 03:15:04.817493

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a485ac72b99a"
down_revision: Union[str, None] = "e4065d67fdff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("registration_date", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"], ["member.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("admin")
    # ### end Alembic commands ###
