FROM python:3
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --upgrade -r /code/requirements.txt
COPY . /code
COPY start_celery.sh /code/start_celery.sh
RUN chmod +x /code/start_celery.sh

ARG POSTGRES_HOST
ARG POSTGRES_PORT
ARG POSTGRES_DB
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG SECRET
ARG ALGORITHM
ARG DOMAIN
ARG API_AUDIENCE
ARG ISSUER

ENV POSTGRES_HOST=$POSTGRES_HOST
ENV POSTGRES_PORT=$POSTGRES_PORT
ENV POSTGRES_DB=$POSTGRES_DB
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PORT=$REDIS_PORT
ENV REDIS_PASSWORD=$REDIS_PASSWORD
ENV SECRET=$SECRET
ENV ALGORITHM=$ALGORITHM
ENV DOMAIN=$DOMAIN
ENV API_AUDIENCE=$API_AUDIENCE
ENV ISSUER=$ISSUER

EXPOSE 8000 5555
CMD ["/code/start_celery.sh"]