version: '3.9'
services:
  uvicorn:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - "8002:8002"
    volumes:
      - .:/code
    depends_on:
      - redis
      - db

  redis:
    image: "redis:alpine"
    env_file:
      - .env
    ports:
      - "6379:6379"

  db:
    image: "postgres:13"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: