name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - BE-20-add-github-actions
      - develop

jobs:
  test-and-deploy:
    name: Test, Lint, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black code formatter
        run: |
          black .

      - name: Run tests
        run: |
          pytest app/tests

      - name: Build Docker image
        run: |
          docker build \
            --build-arg POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
            --build-arg POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
            --build-arg POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
            --build-arg POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            --build-arg REDIS_HOST=${{ secrets.REDIS_HOST }} \
            --build-arg REDIS_PORT=${{ secrets.REDIS_PORT }} \
            --build-arg REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
            --build-arg SECRET=${{ secrets.SECRET }} \
            --build-arg ALGORITHM=${{ secrets.ALGORITHM }} \
            --build-arg DOMAIN=${{ secrets.DOMAIN }} \
            --build-arg API_AUDIENCE=${{ secrets.API_AUDIENCE }} \
            --build-arg ISSUER=${{ secrets.ISSUER }} \
            -t my-fastapi-app .
