name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - BE-20-add-github-actions
      - develop

jobs:
  test-and-deploy:
    name: Test, Lint, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black code formatter
        run: |
          black .

      - name: Build Docker image
        run: |
          docker build -t my-app-image .

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: /home/${{ secrets.USERNAME }}/app

      - name: Upload .env file to Server
        run: |
          scp -i ${{ secrets.EC2_SSH_KEY }} .env ec2-user@${{ secrets.HOST_DNS }}:/home/ec2-user/app/

      - name: Run tests
        run: |
          pytest app/tests

      - name: Build Docker image
        run: |
           docker build -t my-fastapi-app .

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo yum -y update
            sudo yum -y install docker
            sudo docker stop $(sudo docker ps -q) || true
            sudo docker rm $(sudo docker ps -a -q) || true
            sudo docker pull my-fastapi-app
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo docker run --rm -p 8000:8000 my-fastapi-app