name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - BE-20-add-github-actions
      - develop

jobs:
  test-and-deploy:
    name: Test, Lint, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest app/tests

      - name: Run Black code formatter
        run: |
          black --check .

      - name: Upload .env file to Server
        run: |
          scp -i ${{ secrets.EC2_SSH_KEY }} .env ec2-user@${{ secrets.HOST_DNS }}:/home/ec2-user/app/

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: /home/${{ secrets.USERNAME }}/app

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo yum -y update
            sudo yum -y install python3-pip
            cd /home/${{ secrets.USERNAME }}/app
            pip3 install -r requirements.txt
            nohup uvicorn main:app --host 0.0.0.0 --port 80 &
